source-file ~/.config/tmux/keymaps.conf
set -g default-terminal "tmux-256color"
# set-option -sa terminal-features ',alacritty:RGB'
set -sg escape-time 0
set -s extended-keys on

set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g set-clipboard on
set -g status-position bottom
set -g display-time 2000


# List of plugins
set -g @plugin 'tmux-plugins/tpm'


# themeset -g @tokyo-night-tmux_time_format 12H
# source-file ~/.config/tmux/catppuccin-theme.conf
source-file ~/.config/tmux/theme.conf

# set -g @tmux2k-bg-main "#1e2127" 
# set -g @tmux2k-light-purple '#FF90BE'
# set -g @tmux2k-blue '#6B6EBF'
# set -g @tmux2k-light-blue '#FFFFFF'

# tmux-restoration
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'


# sessionx
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'Space'
set -g @sessionx-preview-ratio '40%'
set -g @sessionx-window-height '80%'


if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
