source-file ~/.config/tmux/keymaps.conf
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',alacritty:RGB'
set -sg escape-time 0
set -s extended-keys on

set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g set-clipboard on
set -g status-position bottom


# List of plugins
set -g @plugin 'tmux-plugins/tpm'


# themeset -g @tokyo-night-tmux_time_format 12H
# source-file ~/.config/tmux/catppuccin-theme.conf

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'onedark'
set -g @tmux2k-icons-only false
set -g @tmux2k-show-powerline true
set -g @tmux2k-start-icon "session"

set -g @tmux2k-window-list-alignment 'left'
set -g @tmux2k-compact-windows false

set -g @tmux2k-left-plugins "window"
set -g @tmux2k-right-plugins "git cpu ram time"
set -g @tmux2k-day-month true
set -g @tmux2k-military-time true

# set -g @tmux2k-bg-main "#1e2127" 
set -g @tmux2k-light-purple '#FF90BE'
set -g @tmux2k-blue '#6B6EBF'
set -g @tmux2k-light-blue '#FFFFFF'

set -g @tmux2k-window-colors "text light_purple"
set -g @tmux2k-cpu-colors "blue light_blue"
set -g @tmux2k-ram-colors "light_purple text"
set -g @tmux2k-time-colors "blue light_blue"

set -g @tmux2k-right-sep ' '
set -g @tmux2k-left-sep  ' '
# set -g @tmux2k-window-left-sep ' ' 
# set -g @tmux2k-window-right-sep '█ '


# tmux-restoration
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'


# sessionx
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'Space'
set -g @sessionx-preview-ratio '40%'
set -g @sessionx-window-height '80%'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
