import = ["~/.config/sesh/sessions.toml"]

[default_session]
startup_command = "fastfetch"
preview_command = "exa -alg --color=always --group-directories-first"

[[session]]
name = "home"
path = "~/"
windows = [ "notes", ]
disable_startup_command = true

[[session]]
name = "sesh-sessions"
path = "~/.config/sesh/"
preview_command = "bat --color=always ~/.config/sesh/sessions.toml"
startup_command = "nvim ~/.config/sesh/sessions.toml"

[[window]]
name = "notes"
startup_script = "nvim -c ':Neorg workspace notes'"

[[window]]
name = "term"
startup_script = "fastfetch"

[[window]]
name = "npm"
startup_script = "npm run dev"

[[window]]
name = "artisan.serve"
startup_script = "php artisan serve"
