# wallpaper {
#     monitor = 
#     path = 
#     fit_mode = cover | contain | tile | fill
#     fit_mode = 60
# }

wallpaper {
    monitor = 
    path = ~/wallpapers/Xero-Plasma25.jpg
    fit_mode = cover
}
splash = false
