[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#6B6EBF'
magenta = '#FF90BE'
cyan    = '#56b6c2'
white   = '#dcdfe4'

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[terminal.shell]
program = "/bin/zsh"

[window]
# history = 10000
# multiplier = 3
# opacity = 1.0
opacity = 0.92

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
